"""Add new fields to auto_reply_rules table

Revision ID: 1029d02b1e41
Revises: 572277b94fa4
Create Date: 2026-01-13 14:44:47.336687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1029d02b1e41'
down_revision = '572277b94fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('schedule_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('business_hours_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('business_days_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('business_hours_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('business_hours_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.drop_column('business_hours_end')
        batch_op.drop_column('business_hours_start')
        batch_op.drop_column('business_days_only')
        batch_op.drop_column('business_hours_only')
        batch_op.drop_column('schedule_end')
        batch_op.drop_column('schedule_start')

    # ### end Alembic commands ###
