"""Fix Email model and add missing fields

Revision ID: 10d2edf53b2f
Revises: 
Create Date: 2026-01-07 12:33:47.460543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d2edf53b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger_conditions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('to')

    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger_conditions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
