"""Add content field to follow_ups table

Revision ID: 56deac4e12b6
Revises: a7b66141cd61
Create Date: 2026-01-08 17:30:07.113600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56deac4e12b6'
down_revision = 'a7b66141cd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
