"""Update auto-reply models with explicit relationships

Revision ID: 572277b94fa4
Revises: c3d4e5f6g7h8
Create Date: 2026-01-12 16:13:30.357230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572277b94fa4'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_auto_reply_logs_rule_id_auto_reply_rules', 'auto_reply_rules', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
