"""Critical fixes: Add gmail_id to AutoReplyLog and improve email tracking

Revision ID: 5a9860768110
Revises: cd2c979d336e
Create Date: 2026-02-01 18:35:48.869867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9860768110'
down_revision = 'cd2c979d336e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_auto_reply_logs_gmail_id'), ['gmail_id'], unique=False)
        batch_op.drop_column('sender_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_email', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_auto_reply_logs_gmail_id'))
        batch_op.drop_column('recipient_email')
        batch_op.drop_column('gmail_id')

    # ### end Alembic commands ###
