"""Add last_sent_email_sync field to User model

Revision ID: 7a185ffaa8ad
Revises: c46e63092a4d
Create Date: 2026-01-28 21:04:16.421560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a185ffaa8ad'
down_revision = 'c46e63092a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sent_email_sync', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_sent_email_sync')

    # ### end Alembic commands ###
