"""Add sender_email to auto_reply_templates table

Revision ID: a7b66141cd61
Revises: fbbc9169a9ed
Create Date: 2026-01-07 22:05:37.347331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b66141cd61'
down_revision = 'fbbc9169a9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.drop_column('sender_email')

    # ### end Alembic commands ###
