"""Add enhanced follow-up system with sequences and logs

Revision ID: b0702beae1f0
Revises: f7827b93863e
Create Date: 2026-01-09 22:32:01.277800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0702beae1f0'
down_revision = 'f7827b93863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('apply_to_all', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipient_emails', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stop_on_reply', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('business_days_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('send_window_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('send_window_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('last_triggered', sa.DateTime(), nullable=True))

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_type', sa.Enum('NO_REPLY', 'NO_OPEN', 'NO_CLICK', name='triggertype'), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.Enum('AI_GENERATED', 'TEMPLATE_BASED', name='messagetype'), nullable=True))
        batch_op.add_column(sa.Column('sequence_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stop_on_reply', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('business_days_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('send_window_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('send_window_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_column('send_window_end')
        batch_op.drop_column('send_window_start')
        batch_op.drop_column('business_days_only')
        batch_op.drop_column('stop_on_reply')
        batch_op.drop_column('sequence_number')
        batch_op.drop_column('message_type')
        batch_op.drop_column('trigger_type')

    with op.batch_alter_table('follow_up_rules', schema=None) as batch_op:
        batch_op.drop_column('last_triggered')
        batch_op.drop_column('send_window_end')
        batch_op.drop_column('send_window_start')
        batch_op.drop_column('business_days_only')
        batch_op.drop_column('stop_on_reply')
        batch_op.drop_column('recipient_emails')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('apply_to_all')
        batch_op.drop_column('message_type')
        batch_op.drop_column('trigger_type')

    # ### end Alembic commands ###
