"""Add skip_reason to ScheduledAutoReply and is_apply_to_all_rule method to AutoReplyRule

Revision ID: c7beaa7a4f98
Revises: 5a9860768110
Create Date: 2026-02-04 20:56:22.474468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7beaa7a4f98'
down_revision = '5a9860768110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_auto_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_auto_replies', schema=None) as batch_op:
        batch_op.drop_column('skip_reason')

    # ### end Alembic commands ###
