"""Add message_id column to emails table

Revision ID: cd2c979d336e
Revises: d03c0cbdd04f
Create Date: 2026-02-01 11:07:21.529469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2c979d336e'
down_revision = 'd03c0cbdd04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('folder', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))
        batch_op.drop_column('sync_status')
        batch_op.drop_column('folder')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
