"""Add message_id to auto_reply_log

Revision ID: d03c0cbdd04f
Revises: fa5db19bbd34
Create Date: 2026-01-29 22:03:51.463641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03c0cbdd04f'
down_revision = 'fa5db19bbd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.drop_column('cooldown_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooldown_hours', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
