"""Make email_id and thread_id nullable in FollowUp model and add failed status

Revision ID: ea830a84a3bb
Revises: 56deac4e12b6
Create Date: 2026-01-09 10:39:34.161725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea830a84a3bb'
down_revision = '56deac4e12b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.alter_column('email_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('thread_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
