"""Add delay_reply and from_email fields to auto_reply templates and logs

Revision ID: f7827b93863e
Revises: ea830a84a3bb
Create Date: 2026-01-09 11:57:10.503967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7827b93863e'
down_revision = 'ea830a84a3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_successful', sa.Boolean(), nullable=True))

    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_reply', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        batch_op.drop_column('delay_reply')

    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        batch_op.drop_column('is_successful')
        batch_op.drop_column('from_email')

    # ### end Alembic commands ###
