"""Update DraftEmail model and add DraftAttachment table

Revision ID: fa5db19bbd34
Revises: 7a185ffaa8ad
Create Date: 2026-01-28 21:46:12.985716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5db19bbd34'
down_revision = '7a185ffaa8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bcc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('html_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_emails', schema=None) as batch_op:
        batch_op.drop_column('synced_at')
        batch_op.drop_column('html_body')
        batch_op.drop_column('bcc')
        batch_op.drop_column('cc')

    # ### end Alembic commands ###
