"""Add max_count to follow_ups table

Revision ID: fbbc9169a9ed
Revises: 10d2edf53b2f
Create Date: 2026-01-07 14:02:25.599749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbc9169a9ed'
down_revision = '10d2edf53b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_count', sa.Integer(), nullable=True))
        batch_op.alter_column('sent_email_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.alter_column('sent_email_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('max_count')

    # ### end Alembic commands ###
