"""Manual update for auto-reply models

Revision ID: c3d4e5f6g7h8
Revises: b0702beae1f0
Create Date: 2026-01-10 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6g7h8'
down_revision = 'b0702beae1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the auto_reply_rules table if it doesn't exist
    op.create_table('auto_reply_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True, default=5),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('trigger_conditions', sa.Text(), nullable=True),
        sa.Column('delay_minutes', sa.Integer(), nullable=True, default=0),
        sa.Column('cooldown_hours', sa.Integer(), nullable=True, default=24),
        sa.Column('reply_once_per_thread', sa.Boolean(), nullable=True, default=True),
        sa.Column('prevent_auto_reply_to_auto', sa.Boolean(), nullable=True, default=True),
        sa.Column('ignore_mailing_lists', sa.Boolean(), nullable=True, default=True),
        sa.Column('stop_on_sender_reply', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_triggered', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['template_id'], ['auto_reply_templates.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Now update auto_reply_logs table
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='Sent', nullable=False))
        batch_op.add_column(sa.Column('skip_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reply_content', sa.Text(), nullable=True))
        
        # Update existing records to have default status
        op.execute("UPDATE auto_reply_logs SET status = 'Sent' WHERE status IS NULL")
        
        # Drop old columns
        batch_op.drop_column('details')
        batch_op.drop_column('from_email')
        batch_op.drop_column('is_successful')
        batch_op.drop_column('action')
    
    # Add foreign key for rule_id with explicit name
    op.create_foreign_key(
        'fk_auto_reply_logs_rule_id',
        'auto_reply_logs', 'auto_reply_rules',
        ['rule_id'], ['id']
    )
    
    # Now update auto_reply_templates table
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('reply_subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reply_body', sa.Text(), nullable=False, server_default=''))
        
        # Migrate data from old columns to new ones
        op.execute("UPDATE auto_reply_templates SET reply_subject = subject WHERE subject IS NOT NULL")
        op.execute("UPDATE auto_reply_templates SET reply_body = content WHERE content IS NOT NULL")
        
        # Drop old columns
        batch_op.drop_column('subject')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('is_active')
        batch_op.drop_column('schedule_start')
        batch_op.drop_column('schedule_end')
        batch_op.drop_column('delay_reply')
        batch_op.drop_column('trigger_conditions')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse changes to auto_reply_templates
    with op.batch_alter_table('auto_reply_templates', schema=None) as batch_op:
        # Add back old columns
        batch_op.add_column(sa.Column('trigger_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delay_reply', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('schedule_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sender_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        
        # Migrate data back
        op.execute("UPDATE auto_reply_templates SET subject = reply_subject WHERE reply_subject IS NOT NULL")
        op.execute("UPDATE auto_reply_templates SET content = reply_body WHERE reply_body IS NOT NULL")
        
        # Drop new columns
        batch_op.drop_column('reply_body')
        batch_op.drop_column('reply_subject')
    
    # Drop foreign key
    op.drop_constraint('fk_auto_reply_logs_rule_id', type_='foreignkey')
    
    # Reverse changes to auto_reply_logs
    with op.batch_alter_table('auto_reply_logs', schema=None) as batch_op:
        # Add back old columns
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_successful', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('from_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        
        # Drop new columns
        batch_op.drop_column('reply_content')
        batch_op.drop_column('skip_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('rule_id')
    
    # Drop auto_reply_rules table
    op.drop_table('auto_reply_rules')
    
    # ### end Alembic commands ###